GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/notes/1

###
GET http://localhost:3001/api/notes/10

###
DELETE http://localhost:3001/api/notes/1

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
  "content": "example"
}

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{}

###
GET http://localhost:3001/api/unknow
