POST http://localhost:3001/api/login 
Content-Type: application/json

{
  "username": "cazaustre",
  "password": "password"
}

###
POST http://localhost:3001/api/login 
Content-Type: application/json

{
  "username": "unknown",
  "password": "pass"
}

