GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/notes/60979008735726e1436dbc8c

###
GET http://localhost:3001/api/notes/10

###
DELETE http://localhost:3001/api/notes/1

###
POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhemF1c3RyZSIsImlkIjoiNjA5N2NkOTIxZmJlMTFmM2VkOGM1YjU1IiwiaWF0IjoxNjIwNTY4OTQ2fQ.gU2ZvMgLW1Sey7zgCI3S2FGho4geYqIocqoP9vvXhbw

{
  "content": "note example 3 by user with JWT"
}

###
POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization:

{}

###
GET http://localhost:3001/api/unknow
